services:
  - type: web
    name: eagle-vision
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 10000
    healthCheckPath: /
